[package]
name = "gsw"
version = "0.1.0"
edition = "2024"

[dependencies]
ff = { version = "0.13.1", features = ["bits","derive","derive_bits"] }
num-rational = "0.4.2"
num-bigint = "0.4.6"
once_cell = "1.21.3"
prio = { version = "0.17.0", features = ["experimental"] }
rand = "0.9.1"
